
const availableTickers = [
  "NVDA",      // NVIDIA
  "TSLA",      // TESLA
  "AAPL",      // APPLE
  "MSFT",      // MICROSOFT
  "AMZN",      // AMAZON
  "AMD",       // Advanced Micro Devices
  "GOOG",      // ALPHABET
/*   "PSNY",     // POLESTAR */
  "PLTR",      // PALANTIR
  "META",      // META PLATFORMS
/*   "NIO",       // NIO ADR */
  "TSM",       // TAIWAN SEMICONDUCTOR MFG CO
  "KLAR",      // KLARNA GROUP
  "KO",        // COCA-COLA
  "GME",       // GAMESTOP
  "INTC",      // INTEL
  "SPOT",      // SPOTIFY
  "AMC",       // AMC ENTERTAINMENT
  "PFE",       // PFIZER
/*   "O",         // REALTY INCOME REIT */
/*   "NEON",      // NEONODE */
  "NFLX",      // NETFLIX
  "AVGO",      // BROADCOM
  "TTWO",      // TAKE-TWO INTERACTIVE SOFTWARE
  "BABA",      // ALIBABA GROUP ADR
  "XPEV",      // XPENG A ADR
  "MU",        // MICRON TECHNOLOGY
  "V",         // VISA
  "PEP",       // PEPSICO
  "SOFI",      // SOFI TECHNOLOGIES
  "BYND",      // BEYOND MEAT
  "ADBE",      // ADOBE
/*   "ORCL",      // ORACLE */
/*   "COIN",      // COINBASE GLOBAL */
/*   "CRM",       // SALESFORCE */
  "SMCI",      // SUPER MICRO COMPUTER
  "PYPL",      // PAYPAL
  "RBLX",      // ROBLOX
/*   "IONQ",      // IONQ */
  "JPM",       // JP MORGAN CHASE & CO
  "BLK",       // BLACKROCK
  "NKE",       // NIKE
  "LCID",      // LUCID GROUP
  "WMT",       // WALMART
  "T",         // AT&T
/*   "ABBV",      // ABBVIE */
  "MARA",      // MARA HOLDINGS
  "XOM",       // EXXON MOBIL
  "ASML",      // ASML HOLDING
  "SONY",      // SONY ADR
 /*  "PLUG",      // PLUG POWER */
  "CRWD",      // CROWDSTRIKE
  "SBUX",      // STARBUCKS
  "ABCL",      // ABCELLERA BIOLOGICS
  "CVX",       // CHEVRON
  "BAC",       // BANK OF AMERICA
  "RIVN",      // RIVIAN AUTOMOTIVE
  "MRK",       // MERCK & CO
  "GS",        // GOLDMAN SACHS
  "AI",        // C3.AI
  "RTX",       // RTX CORPORATION
  "SHOP",      // SHOPIFY
  "UBER",      // UBER TECHNOLOGIES
  "CAT",       // CATERPILLAR
  "COST",      // COSTCO WHOLESALE
  "ISRG",      // INTUITIVE SURGICAL
];

module.exports = { availableTickers };



/* NVIDIA
TESLA
APPLE
MICROSOFT
AMAZON
Advanced Micro Devices
ALPHABET
POLESTAR
PALANTIR
BERKSHIRE HATHAWAY
META PLATFORMS
NIO ADR
TAIWAN SEMICOND MFG CO
KLARNA GROUP
COCA-COLA
GAMESTOP
INTEL
SPOTIFY
AMC ENTERTAINMENT
MILLICOM INTERNATIONAL CELLUAR
PFIZER
REALTY INCOME REIT
NEONODE
NETFLIX
STRATEGY A
BROADCOM
TAKE-TWO INTERACTIVE SOFTWARE
WALT DISNEY
ALIBABA GROUP ADR
JOHNSON & JOHNSON
XPENG A ADR
OATLY GROUP AB
MICRON TECHNOLOGY
VISA
PEPSICO
SOFI TECHNOLOGIES
UNITHEDHEALTH GROUP
QUANTUM COMPUTING
BEYOND MEAT
ELI LILY
ADOBE
MASTERCARD
ORACLE
COINBASE GLOBAL
SALESFORCE
SUPER MICRO COMPUTER
PAYPAL
D-WAVE QUANTUM
ROBLOX
IONQ
JP MORGAN CHASE & CO
BLACKROCK
PROCTER & GAMBLE
NIKE
ROCKET LAB
LUCID GROUP
RIGETTI COMPUTING
WALMART 
AT&T
ABBVIE
MARA HOLDINGS
AST SPACEMOBILE
SOUNDHOUND AI
EXXON MOBIL
ASML HOLDING
HIMS & HERS HEALTH
SONY ADR
PLUG POWER
ARM HOLDINGS ADR
CROWDSTRIKE
STARBUCKS
AMERICAN EXPRESS
PALA ALTO NETWORKS
ABCELLERA BIOLOGICS
CHEVRON
BANK OF AMERICA
CELCIUS
CRISPR THERAPEUTICS
RIVIAN AUTOMOTIVE
SERVICENOW
BITMINE IMMERSION TECHNOLOGIES
MERCK & CO
GOLDMAN SACHS
C3.AI
RTX CORPORATION
QUALCOMM
SHOPIFY
CLEANSPARK
LOCKHEED MARTIN
ROBINHOOD MARKETS
UBER TECHNOLOGIES
CATERPILLAR
3M
EPR PROPERTIES
COSTCO WHOLESALE
NEBIUS GROUP
OMEGA HEALTCARE INVESTORS
INTUITIVE SURGICAL
COREWEAVE */